[env:h743]
platform = ststm32
board = devebox_h743vitx
framework = arduino
monitor_speed = 115200

extra_scripts = pre:fix_map.py

build_flags =
    -D STM32H743xx
    -finput-charset=UTF-8
    -fexec-charset=UTF-8
